<?php

/**
 * @file
 * Contains firstcustom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function firstcustom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the firstcustom module.
    case 'help.page.firstcustom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('my first drupalconsole module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function firstcustom_theme() {
  return [
    'firstcustom' => [
      'template' => 'firstcustom',
      'render element' => 'children',
    ],
  ];
}
